baseURL = 'https://weay.github.io/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„AIæ—¥å¿—'
theme = 'stack'

[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true

[params.sidebar]
emoji = 'ğŸš€'
subtitle = 'æ¢ç´¢AIçš„æ— é™å¯èƒ½'

[params.sidebar.avatar]
enabled = true
local = false
src = "/img/avatar.jpg"

[params.search]
enabled = true
type = "fuse"

[params.share]
twitter = false
facebook = false
reddit = false
linkedin = false
pinterest = false
email = false
wechat = true

[menu]
[[menu.main]]
identifier = 'home'
name = 'é¦–é¡µ'
url = '/'
weight = -100

[[menu.main]]
identifier = 'posts'
name = 'æ–‡ç« '
url = '/post'
weight = -90

[[menu.main]]
identifier = 'categories'
name = 'åˆ†ç±»'
url = '/categories'
weight = -85

[[menu.main]]
identifier = 'tags'
name = 'æ ‡ç­¾'
url = '/tags'
weight = -80

[[menu.main]]
identifier = "search"
name = "æœç´¢"
url = "/search"
weight = -70

[taxonomies]
tag = 'tags'
category = 'categories'

[outputs]
home = ["HTML", "RSS", "JSON"]